admintool/urls.py
from django.urls import path
from . import views

app_name = "tool"

urlpatterns = [
path("admintool/", views.IndexView.as_view(), name="index"),
path("statistics/", views.StatisticsView.as_view(), name="statistics"),
path("regist/", views.RegistrationView.as_view(), name="regist"),
]

gallery/urls.py
from django.urls import path
from . import views

app_name = "gallery"

urlpatterns = [
    path("", views.IndexView.as_view(), name="index"),
    path("art/", views.ArtView.as_view(), name="art"),
    path("artist/", views.ArtistListView.as_view(), name="artist"),
    path("exbihition/", views.ExbihitionView.as_view(), name="exbihition"),
]

opengallery/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('user.urls')),
    path('', include('gallery.urls')),
    path('', include('admintool.urls')),
]

user/urls.py
from django.urls import path
from . import views

app_name = "artist"

urlpatterns = [
    path("signup/", views.SignUpView.as_view(), name="signup"),
    path("signin/", views.SignInView.as_view(), name="signin"),
    path("application/", views.ArtistView.as_view(), name="application"),
    path("dashboard/", views.DashboardView.as_view(), name="info"),
    path("regist/art/", views.ArtPostView.as_view(), name="art"),
    path("regist/exbihition/", views.ExbihionPostView.as_view(), name="exbihition"),
]

templates/tool/dashboard.html
{% extends 'base.html' %}

{% block title %}
    대시보드
{% endblock %}

{% block content %}
{% load humanize %}

<div class="container mt-4">
    <div class="row">
        <a class="btn btn-sm btn-info" href="{% url "tool:statistics" %}">통계 페이지로</a>
        <a class="btn btn-sm btn-info" href="{% url "tool:regist" %}">작가 등록 처리 페이지로</a>
    </div>
</div>

{% endblock %}

templates/tool/registration.html
{% extends 'base.html' %}

{% block title %}
    작가 등록 신청 처리
{% endblock %}

{% block content %}
<div class="container mt-4">
    <div class="row">
        <a class="btn btn-sm btn-info" href="{% url "tool:statistics" %}">통계 페이지로</a>
        <a class="btn btn-sm btn-info" href="{% url "tool:index" %}">대시 페이지로</a>
    </div>
<div class="row">
    <a class="btn btn-sm btn-success">승인</a>
    <a class="btn btn-sm btn-black">반려</a>
</div>
<div class="row">
    여기에 테이블
</div>
</div>
{% endblock %}

templates/tool/statistics.html
{% extends 'base.html' %}

{% block title %}
    작가 등록 신청 처리
{% endblock %}

{% block content %}
<div class="container mt-4">
    <div class="row">
        <a class="btn btn-sm btn-info" href="{% url "tool:regist" %}">작가 등록 처리 페이지로</a>
        <a class="btn btn-sm btn-info" href="{% url "tool:index" %}">대시 페이지로</a>
    </div>
<div class="row">
    여기에 테이블
</div>
</div>
{% endblock %}