admintool/urls.py
from django.urls import path
from . import views

app_name = "tool"

urlpatterns = [
path("admintool/", views.IndexView.as_view(), name="index"),
path("statistics/", views.StatisticsView.as_view(), name="statistics"),
path("regist/", views.RegistrationView.as_view(), name="regist"),
]

gallery/urls.py
from django.urls import path
from . import views

app_name = "gallery"

urlpatterns = [
    path("", views.IndexView.as_view(), name="index"),
    path("art/", views.ArtView.as_view(), name="art"),
    path("artist/", views.ArtistListView.as_view(), name="artist"),
    path("exbihition/", views.ExbihitionView.as_view(), name="exbihition"),
]

opengallery/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('user.urls')),
    path('', include('gallery.urls')),
    path('', include('admintool.urls')),
]

user/urls.py
from django.urls import path
from . import views

app_name = "artist"

urlpatterns = [
    path("signup/", views.SignUpView.as_view(), name="signup"),
    path("signin/", views.SignInView.as_view(), name="signin"),
    path("application/", views.ArtistView.as_view(), name="application"),
    path("dashboard/", views.DashboardView.as_view(), name="info"),
    path("regist/art/", views.ArtPostView.as_view(), name="art"),
    path("regist/exbihition/", views.ExbihionPostView.as_view(), name="exbihition"),
]

templates/base.html
<!DOCTYPE html>
{% load static %}

<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-u1OknCvxWvY5kfmNBILK2hRnQC3Pr17a+RTT6rIHI7NnikvbZlHgTPOOmMi466C8" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.9.1/font/bootstrap-icons.css">

    <title>Open Gallery | {% block title %}{% endblock %}</title>
    <link href="{% static "css/base.css" %}" rel="stylesheet">
    <script src="{% static "js/base.js" %}"></script> 

</head>
<body>
    <nav class="navbar navbar-expand-lg" style="background-color: #e3f2fd;">
        <div class="container">
          <a class="navbar-brand mb-2 me-4" href="{% url "gallery:index" %}">Open Gallery</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mb-2 me-4 mb-lg-0">
              <li class="nav-item me-2">
                <a class="nav-link" href="{% url "gallery:artist" %}">작가</a>
              </li>
              <li class="nav-item me-2">
                <a class="nav-link" href="{% url "gallery:art" %}">작품</a>
              </li>
            </ul>
            <form class="row row-cols-sm-auto  me-auto  my-2">
              <div class="col-12 p-0">
                <div class="input-group input-group-sm">
                  <input type="text" class="form-control shadow-none" id="inlineFormInputGroupUsername" placeholder="찾아보기">
                </div>
              </div>
              <div class="col-12 p-0">
                <select class="form-select form-select-sm shadow-none" id="inlineFormSelectPref">
                  <option value="1">작품명</option>
                  <option value="2">작가명</option>
                  <option value="3">전시명</option>
                </select>
              </div>
            </form>
            <div class="my-2">
              {% if user.is_authenticated%}
              {% if state == "미신청" %}
              <a href="{% url "artist:application" %}"><button class="btn btn-outline-danger btn-sm mx-2 px-2">작가 등록 신청</button></a>
              {% elif state == "미처리"%}
              <button class="btn btn-outline-info btn-sm mx-2 px-2" disabled>작가 등록 처리중</button>
              {% elif state == "반려"%}
              <button class="btn btn-outline-danger btn-sm mx-2 px-2" disabled>작가 등록 재신청</button>
              {% endif%}
              <button class="nav-item dropdown btn btn-outline-info btn-sm">
                <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                  <b>{{ user.username }}님</b>
                </a>
                <ul class="dropdown-menu">
                  {% if user.is_admin %}
                  <li><a class="dropdown-item" href="{% url "tool:index" %}">관리자 페이지</a></li>
                  <li><hr class="dropdown-divider"></li>
                  {% elif state == "승인"  %}
                  <li><a class="dropdown-item" href="{% url "artist:info" %}">대시보드</a></li>
                  <li><hr class="dropdown-divider"></li>
                  {% endif %}
                  <li><a class="dropdown-item" onclick="signout()">로그아웃</a></li>
                </ul>
              </button>
            {% else %}
              <a href="{% url "artist:signin" %}"><button class="btn btn-outline-info btn-sm mx-2 px-2">로그인</button></a>
              <a href="{% url "artist:signup" %}"><button class="btn btn-outline-info btn-sm px-2">회원가입 후 작가 등록</button></a>
            {% endif %}
          </div>
        </div>

        </div>
      </nav>

    {% block content %}
    {% endblock %}

</body>
</html>

templates/index.html
{% extends 'base.html' %}

{% block title %}
    INDEX
{% endblock %}

{% block content %}
<div class="container mt-4">

index

</div>
{% endblock %}