gallery/urls.py
from django.urls import path
from . import views

app_name = "gallery"

urlpatterns = [
    path("", views.IndexView.as_view(), name="index"),
    path("art/", views.ArtView.as_view(), name="art"),
    path("artist/", views.ArtistListView.as_view(), name="artist"),
    path("exbihition/", views.ExbihitionView.as_view(), name="exbihition"),
]

opengallery/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('user.urls')),
    path('', include('gallery.urls')),
    path('', include('admintool.urls')),
]

user/urls.py
from django.urls import path
from . import views

app_name = "artist"

urlpatterns = [
    path("signup/", views.SignUpView.as_view(), name="signup"),
    path("signin/", views.SignInView.as_view(), name="signin"),
    path("application/", views.ArtistView.as_view(), name="application"),
    path("dashboard/", views.DashboardView.as_view(), name="info"),
    path("regist/art/", views.ArtPostView.as_view(), name="art"),
    path("regist/exbihition/", views.ExbihionPostView.as_view(), name="exbihition"),
]

user/models.py
from django.db import models
from django.contrib.auth.models import BaseUserManager, AbstractBaseUser

class UserManager(BaseUserManager):
    def create_user(self, username, password=None):
        if not username:
            raise ValueError('Users must have an username')
        user = self.model(
            username=username,
        )
        user.set_password(password)
        user.save(using=self._db)
        return user
    
    def create_superuser(self, username, password=None):
        user = self.create_user(
            username=username,
            password=password
        )
        user.is_admin = True
        user.save(using=self._db)
        return user


class User(AbstractBaseUser):
    username = models.CharField("사용자 계정", max_length=20, unique=True)
    password = models.CharField("비밀번호", max_length=128)
    join_date = models.DateTimeField("가입일", auto_now_add=True)

    is_active = models.BooleanField(default=True)
    is_admin = models.BooleanField(default=False)
    
    USERNAME_FIELD = 'username'

    REQUIRED_FIELDS = []
    
    objects = UserManager()
    
    def has_perm(self, perm, obj=None):
        return True
    
    def has_module_perms(self, app_label): 
        return True
    
    @property
    def is_staff(self): 
        return self.is_admin


class Artist(models.Model):

    class Meta:
        db_table = "artist"

    GENDER_CHOICES = (
        ("F", "여성"),
        ("M", "남성")
    )
    user = models.OneToOneField(User, on_delete=models.CASCADE, unique=True)
    name = models.CharField("작가 이름", max_length=16)
    gender = models.CharField("성별", max_length=4, choices=GENDER_CHOICES)
    birth = models.DateField("생일")
    email = models.EmailField("이메일", max_length=80, unique = True)
    phone = models.CharField("연락처", max_length = 18, unique = True)
    create_date = models.DateTimeField(auto_now_add=True)
    is_artist = models.BooleanField(default=None, null=True)

user/views.py
from django.contrib.auth import login, logout, authenticate
from django.shortcuts import redirect
from django.core.paginator import Paginator

from rest_framework.response import Response
from rest_framework.views import APIView
from rest_framework import permissions, status
from rest_framework.renderers import TemplateHTMLRenderer

from .models import Artist as ArtistModel
from gallery.models import Art  as  ArtModel
from gallery.models import Exbihition as ExbihitionModel
from .serializers import UserSerializer, ArtistSerializer, ArtistPostSerializer
from gallery.serializers import ArtSerializer, ExbihitionSerializer
        

class SignUpView(APIView):
    renderer_classes = [TemplateHTMLRenderer]
    template_name = "user/signup.html"

    def get(self, request):
        return Response(status=status.HTTP_200_OK)

    def post(self, request):
        pw1 = request.POST.get("password", "")
        pw2 = request.POST.get("password2", "")
        if pw1 == pw2:
            user_serializer = UserSerializer(data=request.data)
            if user_serializer.is_valid():
                user_serializer.save()
                return redirect("artist:signin")
            print(user_serializer.errors)
            return Response({"error":"이미 존재하는 계정입니다."}, status=status.HTTP_400_BAD_REQUEST)
        return Response({"error":"비밀번호가 일치하지 않습니다."}, status=status.HTTP_400_BAD_REQUEST)


class SignInView(APIView):
    renderer_classes = [TemplateHTMLRenderer]
    template_name = "user/signin.html"

    def get(self, request):
        user = request.user
        if user.is_authenticated:
            return redirect("gallery:index")
        else:
            return Response(status=status.HTTP_200_OK)

    def post(self, request):
        username = request.POST.get("username", "")
        password = request.POST.get("password", "")
        me = authenticate(request, username=username, password=password)
        if me:
            login(request, me)
            return redirect("gallery:index")
        else:
            return Response({"error":"ID 혹은 비밀번호를 확인해주세요."}, status=status.HTTP_401_UNAUTHORIZED)

    def delete(self, request):
        logout(request)
        return Response(status=status.HTTP_200_OK)


class ArtistView(APIView):
    renderer_classes = [TemplateHTMLRenderer]
    template_name = "user/regist/application.html"

    def get(self, request):
        return Response(status=status.HTTP_200_OK)

    def post(self, request):
        form_data = request.POST.copy()

        year = form_data.get("year")
        month = form_data.get("month")
        day = form_data.get("day")
        phone1 = form_data.get("phone1")
        phone2 = form_data.get("phone2")
        phone3 = form_data.get("phone3")

        birth = f"{year}-{month}-{day}"
        phone = f"{phone1}-{phone2}-{phone3}"
        user =  request.user.id

        form_data["birth"] = birth
        form_data["phone"] = phone
        form_data["user"] = user
        form_data["is_artist"] = None

        artist_serializer = ArtistPostSerializer(data=form_data)
        print(form_data)

        if artist_serializer.is_valid():
            artist_serializer.save()
            return redirect("gallery:index")

        return Response(artist_serializer.errors, status=status.HTTP_400_BAD_REQUEST)


class DashboardView(APIView):
    renderer_classes = [TemplateHTMLRenderer]
    template_name = "user/dashboard.html"

    def get(self, request):
        user =  request.user.id
        user_data = ArtistModel.objects.get(user=user)
        art_data = ArtModel.objects.filter(artist=user)
        ex_data = ExbihitionModel.objects.filter(artist=user)
        user_serializer = ArtistSerializer(user_data)
        art_serializer = ArtSerializer(art_data, many=True)
        ex_serializer = ExbihitionSerializer(ex_data, many=True)

        data = {
            "artist": user_serializer.data,
            "art": art_serializer.data,
            "exbihition": ex_serializer.data,
        }
        return Response(data, status=status.HTTP_200_OK)


class ArtPostView(APIView):
    renderer_classes = [TemplateHTMLRenderer]
    template_name = "user/regist/art.html"

    def get(self, request):
        return Response(status=status.HTTP_200_OK)

    def post(self, request):
        user =  request.user.id
        form_data = request.POST.copy()
        form_data["artist"] = user
        art_serializer = ArtSerializer(data=form_data)

        if art_serializer.is_valid():
            art_serializer.save()
            return redirect("artist:info")

        return Response(art_serializer.errors, status=status.HTTP_400_BAD_REQUEST)


class ExbihionPostView(APIView):
    renderer_classes = [TemplateHTMLRenderer]
    template_name = "user/regist/exbihition.html"

    def get(self, request):
        user =  request.user.id
        arts = ArtModel.objects.filter(artist=user)
        art_serialzer = ArtSerializer(arts, many=True)
        return Response({"arts":art_serialzer.data}, status=status.HTTP_200_OK)

    def post(self, request):
        form_data = request.POST.copy()
        user =  request.user.id
        form_data["artist"] = user
        ex_serializer = ExbihitionSerializer(data=form_data)

        if ex_serializer.is_valid():
            ex_serializer.save()
            return redirect("artist:info")
        return Response(ex_serializer.errors, status=status.HTTP_400_BAD_REQUEST)
    

def stateCheck(user_id):
    artist_data = ArtistModel.objects.filter(user=user_id)
    if not artist_data:
        state = "미신청"
    else:
        artist_data = ArtistModel.objects.get(user=user_id)
        if artist_data.is_artist:
            state = "승인"
        elif artist_data.is_artist == None:
            state = "미처리"
        else:
            state = "반려"
        return state

templates/user/regist/application.html
{% extends 'base.html' %}

{% block title %}
    작가 등록 신청
{% endblock %}

{% block content %}
<div class="row mt-4 mx-auto justify-content-md-center">
    <div class="col-lg-4">
        <h1 class="mb-4">작가 등록 신청</h1>
        <form method="post" action="{% url "artist:application" %}">
            {% csrf_token %}
            {% if error %}
                <div class="alert alert-danger" role="alert">
                    {{ error }}
                </div>
            {% endif %}


            <div class="mb-3">
                <label for="name" class="form-label">이름</label>
                <input name="name"  type="text" class="form-control shadow-none" placeholder="홍길동">
              </div>
              
              <div class="mb-3">
                  <label for="email" class="form-label">이메일</label>
                  <input name="email"  type="email" class="form-control shadow-none" placeholder="id@domain.com">
                </div>

              <div class="mb-3">
                  <label for="phone" class="form-label">연락처</label>
                  <div class="input-group mb-3">
                    <input name="phone1" type="text" class="form-control text-center" placeholder="010">
                    <span class="input-group-text">-</span>
                    <input name="phone2" type="text" class="form-control text-center" placeholder="1234">
                    <span class="input-group-text">-</span>
                    <input name="phone3" type="text" class="form-control text-center" placeholder="5678">
                  </div>
                </div>
                
                <div class="mb-3">
                    <label for="birth" class="form-label">생년월일</label>
                    <div class="input-group mb-3">
                        <input name="year" type="text" class="form-control text-center" placeholder="2002">
                        <span class="input-group-text">년</span>
                        <input name="month" type="text" class="form-control text-center" placeholder="01">
                        <span class="input-group-text">월</span>
                        <input name="day" type="text" class="form-control text-center" placeholder="01">
                        <span class="input-group-text">일</span>
                    </div>
                </div>
                
                <div class="mb-3">
                    <label for="gender" class="form-label me-4">성별</label>
                    <div class="form-check form-check-inline">
                      <input name="gender" class="form-check-input" type="radio" name="inlineRadioOptions" id="inlineRadio1" value="F">
                      <label class="form-check-label" for="gender">여성</label>
                    </div>
                    <div class="form-check form-check-inline">
                      <input name="gender" class="form-check-input" type="radio" name="inlineRadioOptions" id="inlineRadio2" value="M">
                      <label class="form-check-label" for="gender">남성</label>
                    </div>               
                  </div>

            <div class="d-grid gap-2 d-md-flex justify-content-md-end">
                <button class="btn btn-outline-info" type="submit">신청하기</button>
                </button>
            </div>
        </form>
    </div>
</div>
{% endblock %}

templates/user/regist/art.html
{% extends 'base.html' %}

{% block title %}
    작품 등록
{% endblock %}

{% block content %}
<div class="row mt-4 mx-auto justify-content-md-center">
    <div class="col-lg-4">
        <h1 class="mb-4">작품 등록</h1>
        <form method="post" action="{% url "artist:art" %}">
            {% csrf_token %}
            {% if error %}
                <div class="alert alert-danger" role="alert">
                    {{ error }}
                </div>
            {% endif %}


            <div class="mb-3">
                <label for="title" class="form-label">제목</label>
                <input name="title"  type="text" class="form-control shadow-none" placeholder="65자 이내의 제목">
              </div>
              
              <div class="mb-3">
                  <label for="size" class="form-label">호수</label>
                  <input name="size"  type="text" class="form-control shadow-none" placeholder="1~500 사이의 작품의 크기에 해당하는 호수">
                </div>

              <div class="mb-3">
                  <label for="price" class="form-label">가격</label>
                  <input name="price"  type="text" class="form-control shadow-none" placeholder="1,000,000">
                </div>

            <div class="d-grid gap-2 d-md-flex justify-content-md-end">
                <button class="btn btn-outline-info" type="submit">등록하기</button>
                </button>
            </div>
        </form>
    </div>
</div>
{% endblock %}

templates/user/regist/exbihition.html
{% extends 'base.html' %}

{% block title %}
    전시 등록
{% endblock %}

{% block content %}
<div class="row mt-4 mx-auto justify-content-md-center">
    <div class="col-lg-4">
        <h1 class="mb-4">전시 등록</h1>
        <form method="post" action="{% url "artist:exbihition" %}">
            {% csrf_token %}
            {% if error %}
                <div class="alert alert-danger" role="alert">
                    {{ error }}
                </div>
            {% endif %}


            <div class="mb-3">
                <label for="title" class="form-label">제목</label>
                <input name="title"  type="text" class="form-control shadow-none" placeholder="65자 이내의 제목">
              </div>
              
              <div class="mb-3">
                  <label for="start" class="form-label">전시 시작일</label>
                  <input name="start"  type="date" class="form-control shadow-none" placeholder="YYYY-MM-DD">
                </div>

              <div class="mb-3">
                  <label for="end" class="form-label">전시 종료일</label>
                  <input name="end"  type="date" class="form-control shadow-none" placeholder="YYYY-MM-DD">
                </div>

              <div class="mb-3">
                  <label for="arts" class="form-label">작품 리스트</label>
                  <div id="form-list">
                    {% for art in arts %}
                    <div class="form-check">
                        <input class="form-check-input" type="checkbox" value="{{art.id}}" name="arts">
                        <label class="form-check-label" for="flexCheckDefault">
                          {{art.title}}
                        </label>
                      </div>
                      {% endfor %}
                  </div>
                </div>

            <div class="d-grid gap-2 d-md-flex justify-content-md-end">
                <button class="btn btn-outline-info" type="submit">등록하기</button>
                </button>
            </div>
        </form>
    </div>
</div>
{% endblock %}